return {
	application_switcher = "custom-alttab",
	application_launcher = "custom-launcher",
	power_options = "xfce4-session-logout",
    wallpaper = "custom-wallpaper",
    bluetooth_options = "blueman-manager",
	terminal = "exo-open --launch TerminalEmulator",
	lock = "custom-lock",
	internet_browser = "exo-open --launch WebBrowser",
	editor = "subl",
	files = "exo-open --launch FileManager",
	check_battery_status = [[bash -c 'acpi']],
	check_vnp_status = [[bash -c "nordvpn status | grep Country | cut -d ' ' -f2- && echo ''"]],
	check_keyboard_status = [[bash -c "localectl status | grep Layout | cut -d ':' -f2- && echo ''"]],
	check_wifi_strengh_status = [[awk 'NR==3 {printf "%3.0f" ,($3/70)*100}' /proc/net/wireless]],
	check_wifi_network_status = [[iwgetid -r]],
	vpn_launcher = "custom-nordvpn-menu",
}
