local input = require("utils.input")
local key, common, vim, metaKey, ctrlKey, altKey, shiftKey =
	input.key, input.common, input.vim, input.metaKey, input.ctrlKey, input.altKey, input.shiftKey

return {
	app_workspace_default = key({ metaKey }, common.Return),
	awesome_help = key({ metaKey }, "F1"),
	awesome_quit = key({ metaKey, ctrlKey }, "q"),
	awesome_restart = key({ metaKey, ctrlKey }, "r"),
	client_close = { key({ altKey }, "F4"), key({ metaKey }, "w") },
	client_float = key({ altKey }, "f"),
	client_full_screen = key({ metaKey }, "F11"),
	client_maximize = key({ metaKey }, common.PageUp),
	client_minimize = key({ metaKey }, common.PageDown),
	client_minimize_all = key({ metaKey, shiftKey }, common.PageDown),
	client_restore_all = key({ metaKey, shiftKey }, common.PageUp),
	client_select_above = { key({ metaKey }, vim.Up), key({ metaKey }, common.Up) },
	client_select_below = { key({ metaKey }, vim.Down), key({ metaKey }, common.Down) },
	client_select_left = { key({ metaKey }, vim.Left), key({ metaKey }, common.Left) },
	client_select_next = key({ metaKey }, "."),
	client_select_prev = key({ metaKey }, ","),
	client_select_right = { key({ metaKey }, vim.Right), key({ metaKey }, common.Right) },
	client_select_urgent = key({ metaKey }, "u"),
	client_swap_master = key({ metaKey }, "m"),
	client_switch = key({ altKey }, "Tab"),
	prefix_workspace_goto = { metaKey },
	prefix_workspace_moveto = { metaKey, shiftKey },
	prefix_workspace_toggle = { metaKey, ctrlKey },
	system_next_wallpaper = key({ metaKey, shiftKey }, "d"),
	system_show_desktop = key({ metaKey }, "d"),
	workspace_find_empty = key({ metaKey }, "n"),
	workspace_move_to_empty = key({ metaKey, shiftKey }, "n"),
	workspace_next = { key({ metaKey, ctrlKey }, vim.Up), key({ metaKey, ctrlKey }, common.Up) },
	workspace_next_layout = key({ altKey }, "r"),
	workspace_prev_layout = key({ altKey, shiftKey }, "r"),
	workspace_previous = { key({ metaKey, ctrlKey }, vim.Down), key({ metaKey, ctrlKey }, common.Down) },
	workspace_relocate = key({ metaKey, shiftKey }, "r"),
	workspace_resize_layout = key({ metaKey }, "r"),
	workspace_switch = key({ metaKey }, "Tab"),
}
